server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: voteguard-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-round-cherry-a1ka1vkl-pooler.ap-southeast-1.aws.neon.tech/voteguard?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_4coEBHeAS7VO}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      leak-detection-threshold: 60000
      validation-timeout: 3000
      max-lifetime: 300000
      auto-commit: false

  jdbc:
    template:
      query-timeout: 30
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds (default)
  session-timeout: 120000 # 2 minutes for center-based voting

# Biometric Service Configuration
biometric:
  service:
    url: ${BIOMETRIC_SERVICE_URL:http://localhost:8001}

# Logging
logging:
  level:
    com.voteguard: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


